Staging
Revature-Cinephiliacs/AdminTools pull request #12
Opened 2021-04-27 22:35 UTC by NNKamel

2021-04-27 22:45 UTC, clarson217 requested changes

2021-04-27 22:45 UTC, clarson217 commented on AdminToolsTests/CustomApplicationFactory.cs
> +    }
Please add a comment on what this is.

2021-04-27 22:52 UTC, NNKamel commented on AdminToolsTests/CustomApplicationFactory.cs
> +    }
Done

2021-04-28 20:32 UTC, clarson217 approved these changes

2021-04-28 21:41 UTC, closed without merging

2021-04-28 21:45 UTC, markmoorerev commented on AdminToolsLogic/Logic/TopicLogic.cs
> +        public List<AffectedSubject> GetSubjects()
comments

2021-04-28 21:46 UTC, markmoorerev commented on AdminToolsModels/LogicModels/ReportModel.cs
> +    public class ReportModel
purpose?

2021-04-28 21:48 UTC, markmoorerev commented on AdminToolsTests/FakeJwtManager.cs
> +    public static class FakeJwtManager
purpose?

2021-04-28 21:49 UTC, markmoorerev commented on Repository/Models/AffectedSubject.cs
> +    public partial class AffectedSubject
purpose?

2021-04-28 21:50 UTC, markmoorerev commented on Repository/Models/Cinephiliacs_AdmintoolsContext.cs
> +                optionsBuilder.UseSqlServer("Server=tcp:cinephiliacs.database.windows.net,1433;Initial Catalog=Cinephiliacs_Admintools;Persist Security Info=False;User ID=kugelsicher;Password=F36UWev
this should be in usersecrets for dev and configured on Azure for prod.

2021-04-28 21:50 UTC, markmoorerev commented on Repository/Models/ResolvedTicket.cs
> +    public partial class ResolvedTicket
purpose?

2021-04-28 21:50 UTC, markmoorerev commented on Repository/Models/Ticket.cs
> +    public partial class Ticket
purpose?

2021-04-28 21:51 UTC, markmoorerev commented on Repository/TopicsRepository.cs
> +    public class TopicsRepository
purpose?

2021-04-28 21:52 UTC, markmoorerev requested changes
comments and connection string